//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Coffe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Coffe()
        {
            this.Customization = new HashSet<Customization>();
            this.OrderCoffe = new HashSet<OrderCoffe>();
        }
    
        public int ID_Coffe { get; set; }
        public string Name_Coffe { get; set; }
        public string Type_Of_Coffee { get; set; }
        public bool Ice { get; set; }
        public Nullable<int> Type_Coffee_ID { get; set; }
        public Nullable<int> Amount_Price { get; set; }
    
        public virtual Type_Coffee Type_Coffee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Customization> Customization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderCoffe> OrderCoffe { get; set; }
    }
}
