//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customization
    {
        public Nullable<int> Coffe_ID { get; set; }
        public Nullable<int> Product_ID { get; set; }
        public int ID_Customization { get; set; }
    
        public virtual Coffe Coffe { get; set; }
        public virtual Products Products { get; set; }
    }
}
