//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Type_Coffee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Type_Coffee()
        {
            this.Coffe = new HashSet<Coffe>();
        }
    
        public int ID_Type_Coffee { get; set; }
        public string Type_Coffee_Name { get; set; }
        public Nullable<int> PRICE_Type_Coffee { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Coffe> Coffe { get; set; }
    }
}
