//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COFFE
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public int ID_User { get; set; }
        public string Username { get; set; }
        public string Password_Users { get; set; }
        public Nullable<int> Role_ID { get; set; }
    
        public virtual Roles Roles { get; set; }
    }
}
